### ISSUE TITLE
[BUG] The first issues

### ISSUE THREAD

**Issue by KarstenPH** [KarstenPH/karstenph.github.io#1]
This is basically just a compilation of all issues condensed into one issue to save space (i know you are going to solve this cyan I'm just putting it here)

[legacy mode goes to the void (means that it does nothing)](https://github.com/KarstenPH/karstenph.github.io/issues/1)

![image](https://user-images.githubusercontent.com/66064356/165655726-c77164ff-b0b6-4fbd-8704-234241aab473.png)
Font color is off

![image](https://user-images.githubusercontent.com/66064356/165655765-592ffae8-140a-477e-abe7-75f70e3afa05.png)
Hover does not work for other buttons

![image](https://user-images.githubusercontent.com/66064356/165655840-73a67767-5208-4927-9a40-023f477dc000.png)
No color for the "Others" buttons

![image](https://cdn.discordapp.com/attachments/964350370233081876/969039061543170078/unknown.png)
Color is reversed

![image](https://user-images.githubusercontent.com/66064356/165655915-36e7ca37-f5f9-4428-814e-5a2cf0b91edf.png)
Wrong colors for this section's buttons and the spacing between the "Dead aegisub website" notice (Ill call it that for now) is wrong
(actually the margins are wrong for alot of elements but whatever that will be fixed later)

([THIS WEBSITE](https://karstenph.github.io/) IS A WORK IN PROGRESS, THIS IS ONLY MEANT TO SHOW PROGRESS ON THE SITE AND WHAT SHOULD BE FIXED)

**Comment by cyan-2048** [comment]
the color being "off" is probably because you have force dark mode turned on, after searching for an answer there's no actual proper way to disable force dark mode automatically, force dark mode is non-standard 

Browser tested: Ungoogled Chromium
rewrite:
![image](https://user-images.githubusercontent.com/72785466/165733264-7a9bbce8-5e1d-4ac6-bdbd-b76e470fd750.png)
tested: Firefox
![image](https://user-images.githubusercontent.com/72785466/165735248-f87f8ad8-7567-4239-a119-7c1087fc4ca3.png)

original:
![image](https://user-images.githubusercontent.com/72785466/165733293-a5a43680-2768-4bc2-8cd3-54a095627528.png)

legacy mode has not been decided, it will go to javascript:void(0) because this is the safest way of making "link" elements where it will not redirect to something. Please contact me in discord for the ideas...

i will fix the margin asap and colors for the bottom area asap

**Comment by KarstenPH** [comment]
> the color being "off" is probably because you have force dark mode turned on, after searching for an answer there's no actual proper way to disable force dark mode automatically, force dark mode is non-standard
> 
> Browser tested: Ungoogled Chromium rewrite:
>![image](https://user-images.githubusercontent.com/72785466/165733264-7a9bbce8-5e1d-4ac6-bdbd-b76e470fd750.png)
>tested: Firefox
>![image](https://user-images.githubusercontent.com/72785466/165735248-f87f8ad8-7567-4239-a119-7c1087fc4ca3.png)
> 
>
> original:
>![image](https://user-images.githubusercontent.com/72785466/165733293-a5a43680-2768-4bc2-8cd3-54a095627528.png)
> 
> legacy mode has not been decided, it will go to javascript:void(0) because this is the safest way of making "link" elements where it will not redirect to something. Please contact me in discord for the ideas...
> 
> i will fix the margin asap and colors for the bottom area asap

thanks, just a minor thing to add: add a disclaimer for opera GX users about this issue. This will be closed for now.
